# Generated by Django 3.0.5 on 2021-07-08 22:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import notes.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notes', '0002_note_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folder_name', models.CharField(max_length=300)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dirs', to=settings.AUTH_USER_MODEL)),
                ('parent_folder', models.ForeignKey(max_length=300, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dirs', to='notes.Folder')),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('file_id', models.AutoField(primary_key=True, serialize=False)),
                ('file', models.FileField(max_length=255, null=True, upload_to=notes.models.create_path)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('folder_path', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notes.Folder')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
